# Generated by Django 6.0.3 on 2026-05-01 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inscription", "0004_remove_inscription_unique_student_class_and_more"),
        ("test_bank", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="test",
            name="approved_by",
        ),
        migrations.RemoveField(
            model_name="test",
            name="class_obj",
        ),
        migrations.RemoveField(
            model_name="test",
            name="created_by",
        ),
        migrations.RemoveConstraint(
            model_name="note",
            name="unique_test_student",
        ),
        migrations.AddField(
            model_name="note",
            name="component",
            field=models.CharField(
                choices=[("oral", "Oral"), ("written", "Written")],
                default="oral",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="note",
            name="date",
            field=models.DateField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="note",
            name="inscription",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notes",
                to="inscription.inscription",
            ),
        ),
        migrations.AlterField(
            model_name="note",
            name="mark",
            field=models.FloatField(default=0),
        ),
        migrations.AddConstraint(
            model_name="note",
            constraint=models.UniqueConstraint(
                fields=("inscription", "component"), name="unique_inscription_component"
            ),
        ),
        migrations.RemoveField(
            model_name="note",
            name="student",
        ),
        migrations.RemoveField(
            model_name="note",
            name="test",
        ),
        migrations.DeleteModel(
            name="Test",
        ),
    ]
