# Generated by Django 6.0.3 on 2026-03-28 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("schedule_change", "Schedule Change"),
                            ("payment_reminder", "Payment Reminder"),
                            ("absence_alert", "Absence Alert"),
                            ("meeting", "Meeting"),
                            ("salary", "Salary"),
                            ("general", "General"),
                        ],
                        max_length=25,
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("body", models.TextField()),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.account",
                    ),
                ),
            ],
            options={
                "db_table": "notification",
            },
        ),
        migrations.CreateModel(
            name="NotificationReceiver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="notifications.notification",
                    ),
                ),
                (
                    "receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.account",
                    ),
                ),
            ],
            options={
                "db_table": "notification_receiver",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("notification", "receiver"),
                        name="unique_notification_receiver",
                    )
                ],
            },
        ),
    ]
