# Generated by Django 6.0.3 on 2026-07-12 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_notificationreceiver_is_read_read_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notification",
            options={"ordering": ["-sent_at"]},
        ),
    ]
