# Generated by Django 6.0.3 on 2026-03-28 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academic", "0001_initial"),
        ("persons", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="class",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="persons.teacher"
            ),
        ),
        migrations.AddField(
            model_name="class",
            name="language",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="academic.language"
            ),
        ),
        migrations.AddField(
            model_name="class",
            name="level",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="academic.level"
            ),
        ),
        migrations.AddField(
            model_name="schedule",
            name="class_obj",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="academic.class"
            ),
        ),
        migrations.AddField(
            model_name="schedule",
            name="classroom",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="academic.classroom"
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="schedule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="academic.schedule"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="class",
            unique_together={("name", "start_date")},
        ),
    ]
