# Generated by Django 6.0.3 on 2026-04-10 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='class_obj',
            new_name='class_id',
        ),
    ]
