# Generated by Django 6.0.3 on 2026-04-30 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0003_rename_class_obj_schedule_class_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="schedule",
            old_name="class_id",
            new_name="class_obj",
        ),
    ]
