# Generated by Django 6.0.3 on 2026-08-12 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0004_rename_class_id_schedule_class_obj"),
    ]

    operations = [
        migrations.AlterField(
            model_name="class",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="class",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                    ("scheduled", "Scheduled"),
                ],
                default="scheduled",
                max_length=10,
            ),
        ),
    ]
