# Generated by Django 6.0.3 on 2026-08-13 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0005_alter_class_start_date_alter_class_status"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="class",
            unique_together=set(),
        ),
    ]
