# Generated by Django 6.0.3 on 2026-08-13 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0006_alter_class_unique_together"),
        ("persons", "0004_alter_employee_options_alter_parent_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="class",
            name="academic_year",
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="class",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AddConstraint(
            model_name="class",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ["active", "completed", "cancelled", "scheduled"])
                ),
                name="class_chk_1",
            ),
        ),
    ]
