# Generated by Django 6.0.3 on 2026-08-13 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0007_class_academic_year_alter_class_name_and_more"),
        ("persons", "0004_alter_employee_options_alter_parent_options_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="class",
            name="class_chk_1",
        ),
        migrations.AddConstraint(
            model_name="class",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ["active", "completed", "cancelled", "scheduled"])
                ),
                name="class_status_valid_chk",
            ),
        ),
    ]
