# Generated by Django 6.0.3 on 2026-08-13 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0008_remove_class_class_chk_1_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="class",
            name="class_status_valid_chk",
        ),
    ]
