# Generated by Django 6.0.3 on 2026-04-11 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0002_initial"),
        ("persons", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="language",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="academic.language",
            ),
        ),
    ]
