# Generated by Django 6.0.3 on 2026-05-03 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persons", "0002_teacher_language"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="parent",
            name="students",
        ),
        migrations.AddField(
            model_name="student",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="students",
                to="persons.parent",
            ),
        ),
        migrations.DeleteModel(
            name="ParentStudent",
        ),
    ]
