# Generated by Django 6.0.3 on 2026-07-12 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("persons", "0003_remove_parent_students_student_parent_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="employee",
            options={"ordering": ["-person__id"]},
        ),
        migrations.AlterModelOptions(
            name="parent",
            options={"ordering": ["-person__id"]},
        ),
        migrations.AlterModelOptions(
            name="student",
            options={"ordering": ["-person__id"]},
        ),
        migrations.AlterModelOptions(
            name="teacher",
            options={"ordering": ["-employee__person__id"]},
        ),
    ]
