# Generated by Django 6.0.3 on 2026-09-06 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persons", "0004_alter_employee_options_alter_parent_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="status",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
