# Generated by Django 6.0.3 on 2026-04-10 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_rename_class_obj_schedule_class_id'),
        ('inscription', '0001_initial'),
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='inscription',
            name='unique_student_class',
        ),
        migrations.AddField(
            model_name='inscription',
            name='class_id',
            field=models.ForeignKey(db_column='class_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='academic.class'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='inscription',
            constraint=models.UniqueConstraint(fields=('student', 'class_id'), name='unique_student_class'),
        ),
        migrations.RemoveField(
            model_name='inscription',
            name='class_obj',
        ),
    ]
