# Generated by Django 6.0.3 on 2026-04-25 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0002_remove_inscription_unique_student_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('promoted', 'Promoted'), ('repeated', 'Repeated')], default='confirmed', max_length=20),
        ),
    ]
