# Generated by Django 6.0.3 on 2026-04-30 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0004_rename_class_id_schedule_class_obj"),
        ("inscription", "0003_inscription_status"),
        ("persons", "0002_teacher_language"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="inscription",
            name="unique_student_class",
        ),
        migrations.RenameField(
            model_name="inscription",
            old_name="class_id",
            new_name="enrolled_class",
        ),
        migrations.AddConstraint(
            model_name="inscription",
            constraint=models.UniqueConstraint(
                fields=("student", "enrolled_class"),
                name="unique_student_enrolled_class",
            ),
        ),
    ]
