# Generated by Django 6.0.3 on 2026-08-10 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persons", "0004_alter_employee_options_alter_parent_options_and_more"),
        ("saleries", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="salary",
            name="month",
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="salary",
            name="remark",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="salary",
            name="year",
            field=models.PositiveSmallIntegerField(default=2026),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="salary",
            name="payment_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="salary",
            unique_together={("employee", "month", "year")},
        ),
    ]
