# Generated by Django 6.0.3 on 2026-07-12 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="remark",
            field=models.TextField(blank=True, default=""),
        ),
    ]
